wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: steps
      6:
      - 3
    - 1: episodes
      6:
      - 3
    - 1: critic_loss
      5: 1
      6:
      - 1
      - 3
    - 1: average_reward
      5: 2
      6:
      - 1
      - 3
    - 1: episode_reward
      5: 2
      6:
      - 1
      - 3
    python_version: 3.8.10
    start_time: 1650678906
    t:
      1:
      - 1
      - 55
      3:
      - 7
      - 15
      - 16
      4: 3.8.10
      5: 0.12.15
      8:
      - 5
architecture:
  desc: null
  value: DDPG
batch_size:
  desc: null
  value: 64
env:
  desc: null
  value: ddpg
infra:
  desc: null
  value: Ubuntu
learning_rate_actor:
  desc: null
  value: 0.001
learning_rate_critic:
  desc: null
  value: 0.005
